version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080" # Change this port to whatever your backend listens on
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8000:80" # Change this port to whatever your frontend listens on
    networks:
      - app-network
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf

networks:
  app-network:
    driver: bridge
